version: '2'
services:
    fpv-mariadb:
        container_name: fpv-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/fpv/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=fpv
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
